// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	supernodeservice "github.com/LumeraProtocol/supernode/sdk/adapters/supernodeservice"
)

// CascadeServiceClient is an autogenerated mock type for the CascadeServiceClient type
type CascadeServiceClient struct {
	mock.Mock
}

// CascadeSupernodeRegister provides a mock function with given fields: ctx, in, opts
func (_m *CascadeServiceClient) CascadeSupernodeRegister(ctx context.Context, in *supernodeservice.CascadeSupernodeRegisterRequest, opts ...grpc.CallOption) (*supernodeservice.CascadeSupernodeRegisterResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CascadeSupernodeRegister")
	}

	var r0 *supernodeservice.CascadeSupernodeRegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *supernodeservice.CascadeSupernodeRegisterRequest, ...grpc.CallOption) (*supernodeservice.CascadeSupernodeRegisterResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *supernodeservice.CascadeSupernodeRegisterRequest, ...grpc.CallOption) *supernodeservice.CascadeSupernodeRegisterResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*supernodeservice.CascadeSupernodeRegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *supernodeservice.CascadeSupernodeRegisterRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCascadeServiceClient creates a new instance of CascadeServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCascadeServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CascadeServiceClient {
	mock := &CascadeServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
