// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package supernode is a generated GoMock package.
package supernode

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetTopSNsByBlockHeight mocks base method.
func (m *MockService) GetTopSNsByBlockHeight(ctx context.Context, r GetTopSupernodesForBlockRequest) (GetTopSupernodesForBlockResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopSNsByBlockHeight", ctx, r)
	ret0, _ := ret[0].(GetTopSupernodesForBlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopSNsByBlockHeight indicates an expected call of GetTopSNsByBlockHeight.
func (mr *MockServiceMockRecorder) GetTopSNsByBlockHeight(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopSNsByBlockHeight", reflect.TypeOf((*MockService)(nil).GetTopSNsByBlockHeight), ctx, r)
}
